In [132]:
import mdptoolbox
import numpy as np
import time
import random
import stolenmdp

In [133]:
#Build transition matrix
transition1=np.zeros((4,12,12))
#action0=up
#action1=right
#action2=down
#action3=left
s=range(0,12,1)
for i in s:
    #going up
    if i+4<12:
        transition1[0,i,i+4]+=1
    else:
        transition1[0,i,i]+=1
    #going right
    if i+1 not in [12,8,4]:
        transition1[1,i, i+1]+=1
    else:
        transition1[1,i,i]+=1
    #going down
    if i-4>-1:
        transition1[2,i,i-4]+=1
    else:
        transition1[2,i,i]+=1
    #going left
    if i not in [0,4,8]:
        transition1[3,i, i-1]+=1
    else:
        transition1[3,i,i]+=1

reward=np.ones((4,12,12))
reward1=reward*-1
reward1[:,:,10]=100
reward1[:,:,6]= -1000
reward1[:,:,2]=50


In [134]:
#Value Iteration
problem1=mdptoolbox.mdp.ValueIteration(transition1, reward1, 0.8)
#problem1.setVerbose()
problem1.run()
value1=problem1.V
policy1=problem1.policy
print(value1)
print(policy1)
print(problem1.iter)
print(problem1.time)

(248.94831398157268, 313.5883139815727, 248.94831398157268, 313.5883139815727, 313.5883139815727, 394.3883139815727, 495.3883139815727, 394.3883139815727, 394.3883139815727, 495.3883139815727, 495.3883139815727, 495.3883139815727)
(0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 3)
21
0.001230001449584961


In [135]:
#Policy Iteration
problem1=mdptoolbox.mdp.PolicyIteration(transition1, reward1, 0.8, eval_type=1)
#problem1.setVerbose()
problem1.run()
value1=problem1.V
policy1=problem1.policy
print(value1)
print(policy1)
print(problem1.iter)
print(problem1.time)

(253.55991772477225, 318.19991772477226, 253.55991772477225, 318.19991772477226, 318.19991772477226, 398.9999177247723, 499.9999177247723, 398.9999177247723, 398.9999177247723, 499.9999177247723, 499.9999177247723, 499.9999177247723)
(0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 3)
3
0.005764961242675781


In [136]:
#Q Learning
problem1=mdptoolbox.mdp.QLearning(transition1, reward1, 0.8, n_iter=10000)
problem1.setVerbose()
time1=time.time()
problem1.run()
time2=time.time()
value1=problem1.V
policy1=problem1.policy
qtime=time2-time1
print(value1)
print(policy1)
print(qtime)
#print(problem1.iter)
#print(problem1.time)


(44.400637668762776, 239.49332848294802, 249.9984032986945, 230.43092310487037, 3.3257340905434316, 371.39261435191526, 245.59222144788566, 41.72529759028156, 123.97283205200664, 499.3771916159436, 499.9999628343937, 483.96011449944467)
(1, 0, 2, 3, 2, 0, 2, 2, 1, 1, 0, 3)
0.2495739459991455


In [141]:
problem1=stolenmdp.staceyQLearning(transition1, reward1, 0.8, n_iter=10000)
problem1.setVerbose()
time1=time.time()
problem1.run()
time2=time.time()
value1=problem1.V
policy1=problem1.policy
qtime=time2-time1
print(value1)
print(policy1)
print(qtime)
#print(problem1.iter)
#print(problem1.time)


AttributeError: module 'stolenmdp' has no attribute 'staceyQLearning'

In [ ]:
#Q Learning from scratch
q=np.zeros((12,4))
reward1,transition1
iter=100000
eps=0.2
gamma=0.2
alpha=0.2
state=random.randint(0,11)
action=random.randint(0,3)
nstate=np.argmax(transition1[action,state])
prize=reward1[action,state,nstate]
qval=q[state,action]
maxq=np.max(q[nstate,action])
q[state,action]=(1-alpha)*qval+ alpha*(prize+gamma*maxq)
i=0
while i<iter: #iter
    oldstate=state
    state=nstate
    if random.random()<eps:
        action=random.randint(0,3)
    else:
        action=np.argmax(q[state])
    nstate=np.argmax(transition1[action,state])
    prize=reward1[action,state,nstate]
    qval=q[state,action]
    maxq=np.max(q[nstate,action])   
    q[state,action]=(1-alpha)*qval+ alpha*(prize+gamma*maxq)

    i+=1      

valueq=np.amax(q,axis=1)
policyq=np.argmax(q,axis=1)
print(valueq)
print(policyq)
print(q)


[  8.95000012  49.75000045  62.5         49.75092402  -1.23449718
  -1.24975791 125.          -1.24999923  18.95        99.75
 125.          99.75063469]
[1 1 2 3 2 3 0 1 1 1 0 3]
[[  -1.224485      8.95000012   -1.17319693   -1.20447851]
 [  -1.24996311   49.75000045   -1.24999255   -1.22970765]
 [-975.           -1.24999788   62.5          -1.2453806 ]
 [  -1.24999893   -1.24998944   -1.2499978    49.75092402]
 [  -1.23452102 -197.62327059   -1.23449718   -1.24883028]
 [  -1.2498917  -994.34525246   -1.24989997   -1.24975791]
 [ 125.           -1.24999979   62.5          -1.24994193]
 [  -1.24999929   -1.24999923   -1.24999929 -999.84412694]
 [  -1.17319693   18.95         -1.22459145   -1.17319693]
 [  -1.25         99.75         -1.24997712   -1.23415856]
 [ 125.           -1.25       -987.5          -1.24682913]
 [  -1.25         -1.25         -1.24999972   99.75063469]]
