In [113]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
from sklearn.decomposition import FastICA
from sklearn.random_projection import GaussianRandomProjection
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [270]:
#Data loading
strdata=np.loadtxt('energy.csv', delimiter=',', dtype=str)
strdata=strdata[1:,:]
data=strdata.astype('double')

#Dataset 1
data1=data[:,0:-1]
input1=data1[:,0:-1]
input1= MinMaxScaler().fit_transform(input1)
output1=data1[:,-1]
output1[output1>29] = 2
output1[output1>17] = 1
output1[output1>4] = 0 

#Dataset 2
data2=np.delete(data, [2,3,7,8], axis=1)
input2=data2[:,0:-1]
input2= MinMaxScaler().fit_transform(input2)
output2=data2[:,-1]
output2[output2>29] = 2
output2[output2>17] = 1
output2[output2>4] = 0 


In [272]:
####K-Means Clustering
kclusters1= KMeans(random_state=212, n_clusters=3, algorithm="lloyd")
kclus1vals=kclusters1.fit_predict(input1)
kclusperformance1=np.zeros((3,3))
#kclusperformance1[0,1]=2
#print(kclusperformance1)
for i in range(len(kclus1vals)):
    kclusperformance1[kclus1vals[i], int(output1[i])]+=1
    ##X axis is the actual val, y axis is the calculated

print(kclusperformance1)
N=kclus1vals.shape
accuracy= (kclus1vals==output1).sum()/N
print(accuracy)


kclusters2= KMeans(random_state=212, n_clusters=3, algorithm="lloyd")
kclus2vals=kclusters2.fit_predict(input2)
kclusperformance2=np.zeros((3,3))
#kclusperformance1[0,1]=2
#print(kclusperformance1)
for i in range(len(kclus2vals)):
    kclusperformance2[kclus2vals[i], int(output2[i])]+=1
    ##X axis is the actual val, y axis is the calculated

print(kclusperformance2)
N=kclus2vals.shape
accuracy= (kclus2vals==output2).sum()/N
print(accuracy)

[[351.  33.   0.]
 [  4.  70. 118.]
 [  2.  68. 122.]]
[0.70703125]
[[274. 110.   0.]
 [  0.  46. 146.]
 [  0.  44. 148.]]
[0.609375]


In [274]:

#####EM Clustering
emclusters1= GaussianMixture(random_state=212, n_components=3)
emclusters1.fit(input1)
emvals1=emclusters1.predict(input1)

emperform1=np.zeros((3,3))
for i in range(len(emvals1)):
    emperform1[emvals1[i], int(output1[i])]+=1
    ##X axis is the actual val, y axis is the calculated

print(emperform1)
N=emvals1.shape
accuracy= (emvals1==output1).sum()/N
print(accuracy)

##########################################
emclusters2= GaussianMixture(random_state=212, n_components=3)
emclusters2.fit(input2)
emvals2=emclusters2.predict(input2)

emperform2=np.zeros((3,3))
for i in range(len(emvals2)):
    emperform2[emvals2[i], int(output2[i])]+=1
    ##X axis is the actual val, y axis is the calculated

print(emperform2)
N=emvals2.shape
accuracy= (emvals2==output2).sum()/N
print(accuracy)

###Values
#kclusters1.labels_
#kclusters1.cluster_centers_

[[351.  33.   0.]
 [  6.  66.  96.]
 [  0.  72. 144.]]
[0.73046875]
[[274. 110.   0.]
 [  0.  46. 146.]
 [  0.  44. 148.]]
[0.609375]


In [275]:
###PCA
pca1=PCA(n_components=7, random_state=212)
pcadata1=pca1.fit(input1)
pcadata1= pca1.transform(input1)
print(pca1.components_)
print(pca1.explained_variance_)


pca2=PCA(n_components=4, random_state=212)
pca2.fit(input2)
pcadata2= pca2.transform(input2)
print(pca2.components_)
print(pca2.explained_variance_)



[[ 3.58577524e-01 -3.72555005e-01  5.91546821e-02 -5.42749204e-01
   6.59203271e-01 -3.37632430e-18 -6.52264480e-17 -5.69961281e-17]
 [ 9.10729825e-17  2.64188034e-16 -3.73529453e-16 -1.64114296e-16
  -7.01341566e-18 -1.00000000e+00 -1.55431223e-15 -4.02455846e-16]
 [ 1.21004125e-16  2.53670687e-16 -4.15375570e-16 -8.50528040e-17
  -8.60305702e-17  1.05471187e-15 -8.11461340e-01 -5.84406104e-01]
 [-3.73750511e-01  3.62850393e-01  8.13127868e-01 -1.48632263e-01
   2.13029738e-01 -2.19039399e-16  4.57383048e-16 -1.14319683e-15]
 [-4.02221481e-16  3.94782009e-16  1.02132336e-15 -2.18559887e-16
   1.82641316e-16  3.33066907e-16 -5.84406104e-01  8.11461340e-01]
 [ 4.13509509e-01 -1.31468465e-01  3.50092156e-01 -4.47585185e-01
  -6.99163010e-01 -4.94599707e-17  3.92077819e-17 -1.06657116e-16]
 [-7.48827484e-01 -4.32100635e-01 -1.84193268e-01 -4.32872749e-01
  -1.76749721e-01 -4.13417110e-17 -5.53600654e-17 -4.58033541e-17]]
[5.56548491e-01 1.39069970e-01 1.26768352e-01 9.32975812e-02
 8.0373

In [276]:

###ICA
ica1=FastICA(n_components=7,random_state=212, max_iter=500)
icadata1=ica1.fit_transform(input1)
print(ica1.components_)
print(icadata1.shape)

ica2=FastICA(n_components=4,random_state=212, max_iter=500)
icadata2=ica2.fit_transform(input2)
print(ica2.components_)
print(icadata2.shape)

/Users/staceywies/opt/miniconda3/lib/python3.9/site-packages/sklearn/decomposition/_fastica.py:494: FutureWarning: Starting in v1.3, whiten='unit-variance' will be used by default.
  warnings.warn(


[[ 8.88418535e-01  4.97126656e-01  1.29007110e-01  5.62496677e-01
   2.41472715e-01 -1.54816404e-16 -1.02108924e-16 -9.85205404e-17]
 [ 2.63625752e-15  1.41380357e-15  5.52267525e-16  1.44108523e-15
   5.31868619e-16  9.68245837e-02 -8.67043397e-18  1.68653120e-17]
 [-1.60876136e-15 -8.41310500e-16 -3.19607321e-16 -9.22568696e-16
  -3.37611666e-16 -9.83185422e-18  1.25989840e-02 -1.18533114e-01]
 [-1.43896252e-01 -6.39054144e-02 -2.50491662e-02 -6.57245343e-02
  -8.24931696e-02 -3.86807700e-18  1.85048780e-17 -3.10415508e-17]
 [-4.26706662e-01 -3.80305395e-01 -1.16918882e-01 -4.16136952e-01
  -3.09210556e-01 -3.60788159e-17 -5.37080908e-17 -1.41414862e-17]
 [-1.58722018e-15 -7.71797505e-16 -2.63745096e-16 -8.45902246e-16
  -2.78528739e-16  1.21439183e-17 -1.10243267e-01  1.19909228e-02]
 [ 7.75571318e-01  3.60840831e-01  3.02486158e-01  2.45854096e-01
  -4.24635002e-02  1.28932357e-17  5.08911700e-17 -1.99875605e-17]]
(768, 7)
[[-4.40465827e-09  2.64032005e-09  2.37210435e-08 -1.566866

/Users/staceywies/opt/miniconda3/lib/python3.9/site-packages/sklearn/decomposition/_fastica.py:120: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(
/Users/staceywies/opt/miniconda3/lib/python3.9/site-packages/sklearn/decomposition/_fastica.py:494: FutureWarning: Starting in v1.3, whiten='unit-variance' will be used by default.
  warnings.warn(


In [277]:

###Randomized Projections
randproj1=GaussianRandomProjection(n_components=7,random_state=212)
randproj1.fit(input1)
randprojdata1=randproj1.transform(input1)
print(randproj1.components_)
print(randprojdata1.shape)


randproj2=GaussianRandomProjection(n_components=4,random_state=212)
randproj2.fit(input2)
randprojdata2=randproj2.transform(input2)
print(randproj2.components_)
print(randprojdata2.shape)



[[ 0.08668499 -0.05623999 -0.42877997 -0.4063447  -0.13840766 -0.35979091
  -0.32452587 -0.25692058]
 [ 0.26020986  0.07363194 -0.1695665   0.19059433 -0.22137466  0.15719092
   0.07196112  0.25423218]
 [ 0.30629064  0.60932408 -0.9294307   0.1009481   0.11142524  0.40522306
   0.32411221  0.42159442]
 [ 0.25851339  0.25947226 -0.02176783  0.07904684  0.15143091 -0.46607153
   0.30158847 -0.04135447]
 [-0.1380749  -0.24532662 -0.41619178  0.05160203 -0.2095689   0.64235955
   0.01388682  0.14237921]
 [ 0.3644904   0.08185437  0.08936556 -0.26388072 -0.07558831 -0.35315038
   0.42111698  0.68102659]
 [-0.05710643  0.19678354 -0.30275292  0.2957501   0.52430327 -0.29366153
   0.36274447  0.26384844]]
(768, 7)
[[ 0.11467346 -0.07439851 -0.56722259 -0.53754351 -0.18309612]
 [-0.47595864 -0.42930737 -0.33987398  0.34422529  0.0974059 ]
 [-0.2243154   0.2521326  -0.29285115  0.20794404  0.09519561]
 [ 0.33631756  0.40518444  0.80606    -1.22952125  0.13354179]]
(768, 4)


In [280]:
##Linear Discriminant Analysis
lda1=LinearDiscriminantAnalysis(n_components=2)
ldadata1=lda1.fit_transform(input1, output1)
print(lda1.coef_)
print(ldadata1.shape)

lda2=LinearDiscriminantAnalysis(n_components=2)
ldadata2=lda2.fit_transform(input2, output2)
print(lda2.coef_)
print(ldadata2.shape)

[[-4.51427048e+00 -4.77025097e+00 -4.20843825e+00 -2.58590792e+00
  -1.65959706e+01 -2.53404701e-02 -3.87228033e+00  3.00753611e-01]
 [ 2.32196789e+01  1.36181897e+01  6.51582232e+00  1.36495905e+01
   1.38402741e+01  8.25635750e-02  9.07825291e-01 -4.72474382e-01]
 [-9.82904390e+00 -2.60721187e+00  1.61752849e+00 -5.87879519e+00
   1.48253110e+01 -2.11325979e-02  5.11319147e+00 -1.10733000e-01]]
(768, 2)
[[-12.79000465 -18.47271385 -13.55147751  -0.28369596  -3.7644174 ]
 [  7.16336968   7.82249436  -0.18409184   0.06108162  -0.17311489]
 [  7.0468957   11.89464191  12.75484083   0.22284479   3.62609982]]
(768, 2)


In [286]:
data1=[pcadata1, icadata2,randprojdata1, ldadata1]
data2=[pcadata2, icadata2, randprojdata2, ldadata2]

for dat in data1:
    cluster=KMeans(random_state=212, n_clusters=3)
    clustervals=cluster.fit_predict(dat)
    clusterperformance=np.zeros((3,3))
    for i in range(len(clustervals)):
        clusterperformance[clustervals[i], int(output1[i])]+=1
        ##X axis is the actual val, y axis is the calculated
    #print(clusterperformance)
    N=clustervals.shape
    accuracy= (clustervals==output1).sum()/N
    print(accuracy)

    emclusters= GaussianMixture(random_state=212, n_components=3)
    emclusters.fit(dat)
    emvals=emclusters.predict(dat)

    emperform=np.zeros((3,3))
    for i in range(len(emvals)):
        emperform[emvals[i], int(output1[i])]+=1
        ##X axis is the actual val, y axis is the calculated

    #print(emperform)
    N=emvals.shape
    accuracy= (emvals==output1).sum()/N
    print(accuracy)

for dat in data2:
    cluster=KMeans(random_state=212, n_clusters=3)
    clustervals=cluster.fit_predict(dat)
    clusterperformance=np.zeros((3,3))
    for i in range(len(clustervals)):
        clusterperformance[clustervals[i], int(output2[i])]+=1
        ##X axis is the actual val, y axis is the calculated
    #print(clusterperformance)
    N=clustervals.shape
    accuracy= (clustervals==output1).sum()/N
    print(accuracy)
    emclusters= GaussianMixture(random_state=212, n_components=3)
    emclusters.fit(dat)
    emvals=emclusters.predict(dat)

    emperform=np.zeros((3,3))
    for i in range(len(emvals)):
        emperform[emvals[i], int(output2[i])]+=1
        ##X axis is the actual val, y axis is the calculated

    #print(emperform)
    N=emvals.shape
    accuracy= (emvals==output2).sum()/N
    print(accuracy)
    

[0.70703125]
[0.73046875]
[0.0859375]
[0.41015625]
[0.35546875]
[0.05989583]
[0.77213542]
[0.70963542]
[0.03125]
[0.609375]
[0.0859375]
[0.29817708]
[0.59244792]
[0.29817708]
[0.0078125]
[0.19401042]
